ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.pluguns.SerializationKt.configureSerialization
      - com.example.pluguns.SecurityKt.configureSecurity
      - com.example.pluguns.RoutingKt.configureRouting
